# Numpy Tasks

## Task_1

#### Question 1. Create a numpy array with 6X5 2D array from 10 upwards

In [3]:
import numpy as np
arr = np.arange(10,40).reshape((6,5))
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

#### Question 2. From question 1, reshape the numpy array to any shape of your choice and return the max value from each column.

In [35]:
arr.shape = (10, 3)
print(arr)
col1, col2, col3 = arr.max(axis=0)
print(col1)
print(col2)
print(col3)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]
 [37 38 39]]
37
38
39


#### Question 3. Create a numpy array A with np.ones with a shape of (3,4). Create another array using the np.arange with a shape of (3,4). 

In [26]:
ones = np.ones((3, 4))
ran = np.arange(1, 13).reshape((3,4))
print(ones)
print(ran)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Question 4. Perform arithmetic operations (+,-,*,/) on the two arrays from question 3.

In [39]:
sub = ran - ones
add = ran + ones
multi = ran * ones
div = ran / ones
print(sub)
print(add)
print(multi)
print(div)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


#### Question 5. From question 4, transpose the results of each arithmetic operation.

In [38]:
subT = sub.transpose()
addT = add.transpose()
multiT = multi.transpose()
divT = div.transpose()
print(subT)
print(addT)
print(multiT)
print(divT)

[[ 0.  4.  8.]
 [ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]]
[[ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]
 [ 5.  9. 13.]]
[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]
[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]
